version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=recetasuser
      - DB_PASSWORD=recetaspass
      - DB_NAME=recetasdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recetasdb
      MYSQL_USER: recetasuser
      MYSQL_PASSWORD: recetaspass
    ports:
      - "3310:3310"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
